/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.BadConsequence ; 
import NapakalakiGame.SpecificBadConsequence;
import NapakalakiGame.NumericBadConsequence;
import NapakalakiGame.TreasureKind;
import java.util.ArrayList;

/**
 *
 * @author pinguino
 */
public class pendingBadConsequence extends javax.swing.JPanel {
    
    BadConsequence pbModel ; 
    
    public void setPending(BadConsequence Model){
        pbModel = Model ; 
        String visible = "" ;
        String hidden = "" ; 
        ArrayList<TreasureKind> specificVisible = null ; 
        ArrayList<TreasureKind> specificHidden = null ; 
        if (this.pbModel instanceof SpecificBadConsequence){
            specificVisible = ((SpecificBadConsequence) this.pbModel).getSpecificVisibleTreasures() ; 
            specificHidden = ((SpecificBadConsequence) this.pbModel).getSpecificHiddenTreasures() ; 
            for ( TreasureKind tipo :  specificVisible){
                visible += ", " + tipo.name(); 
            }
            visible += "." ; 
            visible.substring(1) ; 
            for ( TreasureKind tipo :  specificHidden){
                hidden += ", " + tipo.name(); 
            }
            hidden += "." ; 
            hidden.substring(1) ;
            
            this.visible.setText(visible) ; 
            this.hidden.setText(hidden);  
        }
        
        else if (this.pbModel instanceof NumericBadConsequence){ 
            this.visible.setText(Integer.toString( ( (NumericBadConsequence) pbModel ).getnVisibleTreasures() )) ; 
            this.hidden.setText(Integer.toString( ( (NumericBadConsequence) pbModel ).getnHiddenTreasures() ));  
        }
        
        else {
            this.visible.setText("TODOS (muerto) ") ; 
            this.hidden.setText("TODOS (muerto) ");
        }
        
        repaint() ; 
        
        }

    /**
     * Creates new form pendingBadConsequence
     */
    public pendingBadConsequence() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textvisible = new javax.swing.JLabel();
        textHidden = new javax.swing.JLabel();
        visible = new javax.swing.JLabel();
        hidden = new javax.swing.JLabel();

        textvisible.setText("Tesoros Visibles: ");

        textHidden.setText("Tesoros Ocultos: ");

        visible.setText("visible");

        hidden.setText("hidden");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textvisible)
                    .addComponent(textHidden)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hidden)
                            .addComponent(visible))))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textvisible)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(visible)
                .addGap(8, 8, 8)
                .addComponent(textHidden)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hidden)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hidden;
    private javax.swing.JLabel textHidden;
    private javax.swing.JLabel textvisible;
    private javax.swing.JLabel visible;
    // End of variables declaration//GEN-END:variables
}
