/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.Prize;

/**
 *
 * @author pinguino
 */
public class PrizeView extends javax.swing.JPanel {

    /**
     * Creates new form PrizeView
     */
    public PrizeView() {
        initComponents();
    }
    Prize prizeModel ; 
    
    public void setPrize(Prize model){
        prizeModel = model ; 
        this.levels.setText(Integer.toString(prizeModel.getLevel())) ;
        this.treasures.setText(Integer.toString(prizeModel.getTreasure())) ;  
        repaint() ; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        treasures = new javax.swing.JLabel();
        levels = new javax.swing.JLabel();
        txttreasures = new javax.swing.JLabel();
        txtlevels = new javax.swing.JLabel();

        treasures.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        treasures.setForeground(new java.awt.Color(209, 42, 42));
        treasures.setText("1");

        levels.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        levels.setForeground(new java.awt.Color(127, 182, 68));
        levels.setText("1");

        txttreasures.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        txttreasures.setForeground(new java.awt.Color(209, 42, 42));
        txttreasures.setText("TREASURES");

        txtlevels.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        txtlevels.setForeground(new java.awt.Color(127, 182, 68));
        txtlevels.setText("LEVELS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txttreasures)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(treasures))
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtlevels)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(levels))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttreasures)
                    .addComponent(treasures))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtlevels)
                    .addComponent(levels)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel levels;
    private javax.swing.JLabel treasures;
    private javax.swing.JLabel txtlevels;
    private javax.swing.JLabel txttreasures;
    // End of variables declaration//GEN-END:variables
}
