/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import NapakalakiGame.Treasure ; 
import java.awt.Color;

/**
 *
 * @author pinguino
 */
public class TreasureView extends javax.swing.JPanel {
    
    private Treasure treasureModel ; 
    
    private boolean selected = false ; 
    
    public boolean isSelected(){ return selected ; } 
    
    public Treasure getTreasure(){ return treasureModel ; } 
    
    public void setTreasure(Treasure model){
        treasureModel = model ; 
        this.bonus.setText(Integer.toString(treasureModel.getBonus())) ;
        this.nombre.setText(treasureModel.getName()) ; 
        this.tipo.setText(treasureModel.getType().name()) ; 
        repaint() ; 
    }

    /**
     * Creates new form TreasureView
     */
    public TreasureView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipo = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        bonus = new javax.swing.JLabel();

        setBackground(new java.awt.Color(98, 152, 211));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        tipo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        tipo.setText("BOTHHANDS");

        nombre.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        nombre.setText("El aparato del Pr. Tesla");

        bonus.setFont(new java.awt.Font("Ubuntu", 3, 52)); // NOI18N
        bonus.setText("4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre)
                    .addComponent(tipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bonus)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipo))
                    .addComponent(bonus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        this.selected = ! this.selected ; 
        if (selected) 
            this.setBackground(Color.red);
        else
            this.setBackground(new Color(98,152,211)); 
        repaint() ; 
        
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bonus;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel tipo;
    // End of variables declaration//GEN-END:variables
}
